### ISSUE TITLE
BGO flood-filling ignores other BGO`s

### ISSUE THREAD

**Issue by Alucard648** [Wohlstand/PGE-Project#185]
If you try to use flood-fill tool with a backgroung object on an area encased with BGO`s like this:
![bgo_flood_fill_1](https://cloud.githubusercontent.com/assets/7596025/6565880/8c4f1034-c6c4-11e4-9b02-cfa538057379.png)
we would end with completely full area with the pillar disregarded and, in this case, destroyed due to overwriting mode enabled.
![bgo_flood_fill_2](https://cloud.githubusercontent.com/assets/7596025/6565909/fef181b2-c6c4-11e4-94b7-1d5baa92a0aa.png)
The same attempt with completely different BGO (like a SMB3 small bush) results in full level flooded with 3-second crash potection timeout kicking in.
Tested on 0.2.2rc.

**Comment by Wohlstand** [comment]
It's true: BGO's of difference BGO-ID aren't colliding (SMBX64 declares this thing). But it's a good reason to add the exception which will work ONLY with flood-filling: BGO's will collide with another BGO's without exclusion.

**Comment by Wohlstand** [comment]
Fixed: https://github.com/Wohlstand/PGE-Project/commit/33356c6f2b67959006e5714fddf3d6c47ff9e91e
