### ISSUE TITLE
Line drawing tool tries to ignore grid snapping

### ISSUE THREAD

**Issue by Alucard648** [Wohlstand/PGE-Project#186]
If you try to use line drawing tool for an item, whose dimensions aren`t a multiple of grid size (in SMBX 32x32 or 32x64, for instance) with grid snapping turned on, this would result in following:
1. The tool tries to place objects while ignoring the grid.
2. Grid snapping kicks in, resulting in misaligned or even outright missing items.
![line_draw_bug](https://cloud.githubusercontent.com/assets/7596025/6566155/9ace9eec-c6c7-11e4-93e5-d2eb57f76e68.png)
In this screenie, all coins are placed, using Line Draw tool only. Red ones are placed with grid snapping mode on and yellow ones are drawn with grid snapping turned off.
Similar problem occurs with Square Fill tool also.
Tested on 0.2.2rc.

**Comment by Wohlstand** [comment]
This thing happening if item side size is not multiple 32 px. But I think, I will improve calculator to keep multiple 32 placements even if size is not

**Comment by Wohlstand** [comment]
Fixed: https://github.com/Wohlstand/PGE-Project/commit/fcda9e1d2a2669a5a1e199c9fc40c28eed828702
